version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: shop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://auth-server:9000/oauth2/jwks
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://auth-server:9000
    depends_on:
      - redis
      - auth-server
    restart: unless-stopped

  market:
    build:
      context: ./market
      dockerfile: Dockerfile
    container_name: market
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - PAYMENT_SERVICE_URL=http://payment:8081
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_PAYMENT-CLIENT_TOKEN-URI=http://auth-server:9000/oauth2/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_PAYMENT-CLIENT_ISSUER-URI=http://auth-server:9000
    depends_on:
      - redis
      - payment
      - auth-server
    restart: unless-stopped


  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    ports:
      - "9000:9000"
    environment:
      - AUTH-SERVER_ISSUER=http://auth-server:9000
    restart: unless-stopped
