spring.application.name=auth-server
server.port=9000
spring.security.oauth2.authorizationserver.issuer=http://auth-server:9000

spring.profiles.active=dev

auth-server.issuer=http://auth-server:9000

auth.client.secret=market-secret
auth.client.key=market-key-1
