spring.application.name=my-market-app
# R2DBC H2 in-memory
spring.r2dbc.url=r2dbc:h2:mem:///shopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=user
spring.r2dbc.password=password
# H2 Console (for debug, uses JDBC)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
# Server
server.port=8080
# Logging
logging.level.com.shop=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.level.ru.yandex.practicum.mymarket.config.SessionUtils=DEBUG