spring.application.name=my-market-app
spring.main.web-application-type=reactive

# R2DBC H2
spring.r2dbc.url=r2dbc:h2:mem:///shopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=user
spring.r2dbc.password=password

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Payment service
payment.service.url=http://localhost:8081

# Server
server.port=8080

# Logging
logging.level.ru.yandex.practicum.mymarket=DEBUG
logging.level.org.springframework.r2dbc=DEBUG

#Security
spring.security.oauth2.client.registration.payment-client.client-id=market-app
spring.security.oauth2.client.registration.payment-client.client-secret=market-secret
spring.security.oauth2.client.registration.payment-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.payment-client.scope=payment.read,payment.write
spring.security.oauth2.client.provider.payment-client.issuer-uri=http://localhost:9000
spring.security.oauth2.client.provider.payment-client.token-uri=http://localhost:9000/oauth2/token