CREATE TABLE IF NOT EXISTS items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    img_path   VARCHAR(500),
    price      BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    BIGINT NOT NULL,
    session_id VARCHAR(128) NOT NULL,
    count      INT NOT NULL DEFAULT 0,
    version    BIGINT,
    UNIQUE (item_id, session_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(128),
    total_sum  BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS order_items (
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id  BIGINT NOT NULL,
    title    VARCHAR(255) NOT NULL,
    price    BIGINT NOT NULL DEFAULT 0,
    count    INT NOT NULL DEFAULT 1
);
