spring.application.name=payment
server.port=8081

spring.r2dbc.url=r2dbc:h2:mem:///paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=user
spring.r2dbc.password=password

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.ru.yandex.practicum.market.payment=DEBUG

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/oauth2/jwks